### PR TITLE
Fix for issue #53 (Handle binary expression - op - literal case)

### PR DESCRIPTION
**Pull request by cgewecke**
This PR is based on analysis and tests of @ulope and @duaraghav8 for issue #53. It checks to see if the left node of lint target is itself a binary expression. If it is, it substitutes the left node's right sub-node for left node in the call to `getStringBetweenNodes` in order to provide the correct start point value. 

*Think* this works without breaking anything (all tests pass). Needs sanity check due to trees.

### CODE REVIEW

**Comment by duaraghav8** [comment]
@cgewecke I designed the project so that one would never have to ```require``` any util files separately inside a rule file. But I forgot to include the ```isASTNode()``` method. However, I've made the necessary changes.

You can use the method like this:

```js
var sourceCode = context.getSourceCode ();

if (sourceCode.isASTNode (object)) { ... }
```

Can you please change the code accordingly?

**Comment by cgewecke** [comment]
I tried to squash commits here and your changes to master are showing up as part of this PR . . . not sure what to do. Please let me know if this is a problem.

**Comment by duaraghav8** [comment]
haha I don't knw how that happened.
I'm closing this one, just create a new PR!

**Comment by cgewecke** [comment]
@duaraghav8  Yes! Thank you. Opening a clean one in a sec.

**Pull request closed without merging**
