### PR TITLE
Show errors in context and improve output readability

### PR DESCRIPTION
**Pull request by federicobond**
I can develop a version for programmatic consumption (useful for integration with text editors and IDEs) if you are interested.

**Preview:**

captura de pantalla 2016-10-29 a las 02 48 46

### CODE REVIEW

**Comment by duaraghav8** [comment]
This looks awesome
Recently, I'd been thinking about integrations with Atom & Consensys' truffle. **Which ones do you have in mind?**

**By programmatic consumption, do you mean its functionality can be exposed as an API to other devs?** Because currently that's how solium works.

Have a look at https://github.com/duaraghav8/Solium/blob/master/lib/solium.js
It exports a function that returns a ```Solium``` object. This object provides several functions like ```lint()```, ```reset()```, ```getSourceCode()```

And ```cli.js``` uses the ```lint()``` functions to get an array of error objects and then pretty-prints (sort of pretty) them.

**Comment by federicobond** [comment]
Yes, sorry I wasn't clear enough. I meant a text output that is easier to parse for computers, like this:

````
contracts/MetaCoin.sol:1:22: warning: empty statement: There should be no character(s) before top-level declaration.
contracts/MetaCoin.sol:3:0: error: Import statement must be at the top of the file.
contracts/MetaCoin.sol:10:0: warning: ContractStatement 'MetaCoin' must be preceded by a 2-line gap.
contracts/MetaCoin.sol:11:7: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:13:1: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:15:1: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:17:0: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:19:1: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:20:37: error: Consequent should exist exactly on the line after condition.
contracts/MetaCoin.sol:25:0: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:27:1: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:27:53: error: Function 'getBalanceInEth': Opening brace must be preceded by only a single space.
contracts/MetaCoin.sol:29:0: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:31:1: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
contracts/MetaCoin.sol:33:0: warning: Incorrect indentation: Make sure you use 4 SPACES per level and don't precede the code by any comments.
````

With this kind of output, it's trivial enough to integrate with `vim`, and probably other editors. We could support json output too, which makes it trivial to integrate with Atom.

**Comment by duaraghav8** [comment]
Oh in that case, would be great if you're willing to implement this feature!

**Comment by federicobond** [comment]
Sure!

**Comment by federicobond** [comment]
@duaraghav8 I am working on a couple of pull requests that build on this.

Could you merge it so it doesn't get too big?

**Comment by duaraghav8** [comment]
@federicobond  sure. sorry, I haven't been very active lately thanks to academic work! So I'll try to familiarise myself with the code you push as quickly as possible, then merge =)

**Pull request merged**
