### PR TITLE
Fix and improve tests. Configure linter

### PR DESCRIPTION
**Pull request by federicobond**
I configured `eslint` and fixed all errors. Some tests were not running because of typos.

The test script in `package.json` is also much cleaner now.

### CODE REVIEW

**Comment by federicobond** [comment]
@duaraghav8 can you setup Travis CI or another build system to run all tests for each pull request?

**Comment by federicobond** [comment]
Hi @duaraghav8, anything blocking this patch?

**Comment by duaraghav8** [comment]
@federicobond sorry for delaying the merge, but I'm keeping track of it. I first have to remove a couple of rules and their tests since me and cgewecke are working on shifting to solidity-parser (have a look here https://github.com/duaraghav8/solparse/issues/15).

Then I'll be re-visiting your PR to make sure nothing breaks and I'll merge.

**Comment by federicobond** [comment]
Great! This is good step forward for code quality. Would you mind configuring Travis so we can run the tests and these checks on each pull request?

If you are too busy I can configure it for you.

**Pull request merged**
