### PR TITLE
Split out whitespace rules into multiple rules.

### PR DESCRIPTION
**Pull request by nuevoalex**
Also split the overflow indentation check into its own rule.

### CODE REVIEW

**Comment by nuevoalex** [comment]
For more context this began because we didn't want to follow the overflow indentation rule where more than 3 elements must be put on individual lines, but couldn't disable it without losing all indentation checking.

This change breaks that rule into a separate rule and does the same with many pieces of the whitespace rule.

**Comment by duaraghav8** [comment]
This is fair, so I'll be merging the PR. But since it introduces a breaking change in `soliumrc`, we'll first be planning out how best to handle that. Although `solium --sync` run by a user will automatically make the rule name changes, we're currently digging for a better alternative, so expect this update to be published in 6-8 days.

**Comment by nuevoalex** [comment]
Awesome. Thank you!

**Comment by duaraghav8** [comment]
thanks for the awesome work @nuevoalex!

**Pull request merged**
