### PR TITLE
Add the packaging metadata to build the solium snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest solium in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

### CODE REVIEW

**Comment by duaraghav8** [comment]
Thanks @elopio, this certainly would be great. But I'm afraid I'll pass on it because:
1. Solium is under heavy development right now and we'll add distribution channels only once it has reached a mature stage.
2. This seems to be a marketing gimmick to me.
Don't get me wrong, I'm sure your intention was to contribute to the project, but we can't add a configuration from a product that we're not fully aware of. So I'll keep this PR open for now.

**Comment by elopio** [comment]
Hello @duaraghav8!

Thanks for taking a look. No marketing gimmick here, I'm maintaining the [solidity snap](https://github.com/ethereum/solidity/blob/develop/snap/snapcraft.yaml) in the Ubuntu store, and I started looking for other useful tools to accompany it. As part of my work in Ubuntu, I have to test our new features each week, so I took solium as a test subject for our snapcraft 2.33 release.

It worked nicely, so I shared the package with you in case you would be interested in making your project a one-command install for Ubuntu users. But I can understand if you are not interested, no hard feelings :)

About solium being under development, we designed the store to have room for that. The resulting snap out of build.snapcraft.io will end up in the edge channel. Snaps are visible for user searches only when they are in the stable channel. This gives your early adopters a very easy way to always have the latest code from the master branch, and provide feedback as you develop. I wrote a little about this here: http://elopio.net/blog/ipfs-crowdtesting/

In the case of solidity, we have the develop branch hooked to the edge channel. And the release branch hooked to the candidate channel. 0.4.15 was our second release to the stable channel in the store. Things are looking good there, with the number of installs slowly growing, around 10 new users per day now.

Please let me know if you have any question. And I'm sorry if it sounded too much like I'm trying to sell you something.

**Comment by duaraghav8** [comment]
@elopio That does give me some confidence! Like I said, this kind of distribution would be great for solium. I'll read up on and play around with Snapcraft a bit more and once confident about usage, I'll merge this PR.
Thanks again:)

**Comment by elopio** [comment]
Thanks for the merge @duaraghav8. Let me know if you need a hand putting it in the store.

pura vida.

**Pull request merged**
